In [1]:
import numpy as np


In [16]:
l=[]
k=[]
for i in range (0,2):
    for i in range(0,2):
        x=int(input("enter number:"))
        l.append(x)
print(l)
m1=np.array([l[0:2],l[2:4]])
print("Matrix 1:","\n",m1)
for t in range (0,2):
    for t in range(0,2):
        y=int(input("enter number:"))
        k.append(y)
print(k)
m2=np.array([k[0:2],k[2:4]])
print("Matrix 2:","\n",m2)
print("Sum:","\n",m1+m2)

enter number: 2
enter number: 3
enter number: 4
enter number: 5


[2, 3, 4, 5]
Matrix 1: 
 [[2 3]
 [4 5]]


enter number: 6
enter number: 7
enter number: 8
enter number: 9


[6, 7, 8, 9]
Matrix 2: 
 [[6 7]
 [8 9]]
Sum: 
 [[ 8 10]
 [12 14]]
